import React from "react";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {faCalendarDays} from '@fortawesome/free-solid-svg-icons';


const CookiePolicy = () => {
    return(
        <div className="flex flex-row gap-8 px-4 py-6 sm:px-8 font-poppins">      
      <div className="flex-1">
        <div
        className="text-3xl whitespace-nowrap text-slate-800 sm:text-4xl md:text-3xl pt-10  font-bold"
        style={{ "line-height": "1" }}
        >
            Cookie Policy
        </div>
        <div className="pt-5 text-lg">
          <FontAwesomeIcon icon={faCalendarDays} className="text-xl mr-2" />Last Updated: June 13, 2024.
        </div>
        <div className="mt-5 font-bold text-xl">
          Types of Cookies and Similar Technologies
        </div>
        <div className="pt-5 font-semibold text-xl">
            Cookies
        </div>
        <div className="pt-3">
        Welcome to our website! We use cookies to enhance your browsing experience. Cookies are<br/>
        small pieces of text sent to your computer or mobile device when you visit our site. These<br/>
        cookies can be delivered by us (first-party cookies) or by third-party partners or suppliers (third-<br/>party cookies). 
        <br/>
        <br/>
        This Cookie Policy explains how HostelHop Platform Ltd. ("Hostelmatch," "we," "us," or "our")<br/>
        collects, uses, cookies when you visit our website at https://www.hostelmatch.com (the<br/>
        "Website") and use our services.
         <br/>
         <br/>
         There are two main types of cookies: session cookies and persistent cookies. Session cookies<br/>
          enable our website to recognize and link your actions during a browsing session. They expire at<br/>
          the end of each session. Persistent cookies help us recognize you as a returning user. These<br/>
          cookies are stored on your system or device until they expire. However, you have the option to<br/>
          delete them before the expiration date if you wish.
        <br/>
        <br/>
        By continuing to use our website, you consent to the use of cookies in accordance with this<br/>
        policy. If you have any questions or concerns about our use of cookies, please contact us at<br/>
        info@hostelmatch.com. 
        <br/>
        <br/>
        Thank you for visiting our site!
        <br/>
        <br/>
        </div>        

        <div className="pt-5 text-xl font-bold underline">
        Other Similar Technologies
        </div>

        <div className="pt-3">          
            <ul className='list-disc p-5 space-y-6'>
              <li><span className="font-bold">Web beacons, gifs, and clear gifs</span> are tiny graphics, each with a unique identifier that are<br/>
                embedded invisibly on sites and in emails. Web beacons allow us to know if a certain page was<br/>
                visited or if ad banners on our sites and other sites are effective. We also use web beacons in<br/>
                our HTML-based emails to let us know whether our emails have been opened by recipients,<br/>
                which helps us to gauge the effectiveness of certain communications, promotions, and<br/>
                marketing campaigns.</li>
              <li><span className="font-bold">Proximity based beacons</span> send one-way signals over very short distances, to communicate<br/>
                with associated mobile apps installed on your phone. They can notify you, for example, about<br/>
                experiences related to your trip and can alert you to related deals or promotions. Beacons <br/>
                communicate with your device only when you are in close proximity and only if you have given<br/>
                consent within the relevant mobile application.</li>
              <li><span className="font-bold">Pixels</span> are small objects embedded into a web page that are not visible to the user. We use<br/>
                pixels to deliver cookies to your computer, facilitate the log-in process, monitor the activity on<br/>
                our sites, and deliver online advertising.</li>
              <li><span className="font-bold">Tags</span> are small pieces of HTML code that tell your browser to request certain content<br/>
                generated by an ad server. We use tags to show you relevant advertising and promotions.</li>
              <li><span className="font-bold">Scripts</span> are pieces of JavaScript code that launch automatically when certain webpages load,<br/>
                to determine whether users view associated advertisements.</li>
              <li><span className="font-bold">Local Storage Objects,</span> such as HTML 5, are used to store content and preferences. Third-<br/>parties with whom we partner to provide certain features on our site to display advertising based<br/>
                upon your web browsing activity use Local Storage Objects to collect and store information.</li>              
            </ul>
            All of the technologies described above will be collectively referred to in this Cookie Statement<br/>
            as “cookies”. 
        </div>

        <div className="mt-2 pt-5 text-xl font-semibold">
            HostelMatch’s Use of Cookies
        </div>

        <div className="pt-3">
        At HostelMatch, we use cookies for a number of reasons, including to:
            <ul className='list-disc p-5 space-y-1'>
              <li>Help us improve your experience when visiting our sites</li>
              <li>Fulfill transactions and ensure our sites perform as intended</li>
              <li>Remember your preferences, such as language, region, or currency</li>
              <li>Provide you with relevant advertising and analyze performance of the ads</li>              
              <li>Enable you to return to previous travel searches</li>              
              <li>Identify errors on our sites</li>              
              <li>Help with data protection and potentially detect and investigate malicious of fraudulent activity</li>              
              <li>Help us understand traffic to our site, including time and date of the visit, time and<br/> date of the last visit, and other information</li>              
              <li>Analyze how well our sites are performing</li>
            </ul>
        </div>

        <div className="pt-5 text-xl font-bold">
        Types of Information Collected by Cookies
        </div>

        <div className="pt-3">
        The types of information that we collect through cookies include:
          <ul className="list-disc p-5 space-y-1">
            <li>IP address</li>
            <li>Device ID</li>
            <li>Viewed pages</li>
            <li>Browser type</li>
            <li>Browsing information</li>
            <li>Operating system</li>
            <li>Internet Service Provider</li>
            <li>Whether you have responded to, or interacted with, an advertisement</li>
            <li>Referring or referred links or URLs</li>
            <li>Features used and activities engaged in on our sites and in our apps</li>
          </ul>
        </div>

        <div className="pt-5 text-xl font-bold underline ">
        Types and Functions of Cookies
        </div>

        <div className="pt-5 text-xl font-semibold">
          Essential Cookies
        </div>

        <div className="pt-3">
        Certain cookies are deemed essential and must be enabled for optimal functionality of our<br/>
        Website. These cookies facilitate critical features such as site navigation and secure user<br/>
        authentication, ensuring a seamless experience for returning users when performing actions like<br/>
        logging in and managing bookings. Opting out of essential cookies is not possible.
        </div>

        <div className="pt-5 text-xl font-semibold">
        Other Categories of Cookies
        </div>

        <div className="pt-3">
        In addition to essential cookies, we utilize various other types to enhance the functionality and<br/>
        user experience of our site:
          <ul className="list-disc p-8 space-y-1">
            <li>Functional Cookies: These cookies enable our Website to retain user preferences,<br/>
            such as language settings, shopping cart contents, and past searches. They serve to<br/>
            enrich and personalize your interaction with our platform.</li>
            <li>Performance Cookies: These cookies aid in identifying and gathering data on user<br/>
            interactions with our Website, allowing us to assess and enhance overall<br/>
            performance. By tracking aggregate user behavior, including page dwell time,
            click-<br/>through rates, search queries, and cursor movements, we can evaluate the
            efficacy<br/> of our advertising, detect technical issues, and refine our services to
            enhance your<br/> browsing experience.</li>
          </ul>
            For analytical purposes, our third-party service providers may utilize cookies to perform their<br/>
            functions, potentially combining the data collected on our site with information obtained<br/>
            elsewhere. It's important to note that this Cookie Statement does not extend to the data<br/>
            practices of these third-party entities.
            <br/>
            <br/>
            <span className="font-semibold">Targeting Cookies:</span> Hostelmatch and our trusted partners utilize these cookies to build<br/>
            personalized user profiles and deliver tailored advertisements based on individual interests.<br/>
            Data is gathered through user interactions with our site, as well as with third-party<br/>
            advertisements on our platform and vice versa. These cookies may control ad frequency,<br/>
            assess campaign effectiveness, and present customized content. It's essential to understand<br/>
            that we do not have access to the cookies managed by our third-party partners, and their data<br/>
            practices are not governed by this Cookie Statement.
            <br/>
            <br/>
            Opting out of targeting cookies may result in less personalized advertising.
        </div>

        <div className="pt-5 text-xl font-bold underline">
        Your Information Choices
        </div>

        <div className="pt-3">
        You can choose not to receive tailored online advertising on this site and other sites and learn<br/>
        more about opting out of having your information used for tailored advertising purposes by<br/>
        accessing one of the following resources:
          <ul className="list-disc p-5 space-y-1">
            <li>For EEA, Switzerland, and UK: http://www.youronlinechoices.eu/</li>
            <li>For Canada: http://youradchoices.ca/choices/</li>
            <li>For U.S. and rest of world:
                <ul className="list-decimal p-3">
                    <li>
                    http://www.aboutads.info/choices/
                    </li>
                    <li>
                    http://optout.networkadvertising.org/  
                    </li>
                </ul>
            </li>
          </ul>
        </div>

        <div className="pt-5 text-xl font-semibold">
        How can you manage your cookies?
        </div>

        <div className="pt-3">
        You are granted the discretion to modify your web browser settings to either permit or decline<br/>
        cookies as you see fit. However, please be advised that should you opt to decline cookies,<br/>
        certain functionalities and sections of our website may become restricted.
        <br/>
        <br/>
        With regard to "Do-Not-Track" signals and analogous mechanisms:
        <br/>
        <br/>
        Some web browsers may transmit "do-not-track" signals to websites with which they interact.<br/>
        Nevertheless, due to disparities in the implementation and activation of this feature across web<br/>
        browsers, it may not always be evident whether users intend for these signals to be transmitted,<br/>
        or if they are even cognizant of their existence. The principal Internet standards-setting body<br/>
        addressing this issue is presently engaged in deliberations to ascertain the appropriate actions<br/>
        websites should undertake upon receipt of such signals.
        <br/>
        <br/>
        At present, we do not undertake specific actions in response to these signals. Upon the<br/>
        establishment and widespread acceptance of a final standard, we will evaluate our website's<br/>
        responses to these signals and revise this Cookie Statement accordingly.
        </div>

        <div className="pt-5 text-xl font-bold">
          Contact Us
        </div>

        <div className="pt-3">
          If you have any questions or concerns about our use of your personal information, cookie<br/>
          policies, please contact us at info@hostelmatch.com
          <br/>
          <br/>
          For more information about our terms and conditions, please refer to our <a href="/privacy_policy" className="underline text-blue-600 hover:text-blue-800 visited:text-purple-600">policy.</a> 
        </div>

        <div className="pt-5 text-xl font-bold">
        Updates to Statement
        </div>

        <div className="pt-3">
        We may update this Statement in response to changing laws or technical or business<br/>
        developments. If we propose to make any material changes, we will notify you by means of a<br/> notice on this page. You can see when this Cookie Statement was last updated by checking the<br/>
        “last updated” date displayed at the top of this Statement. 
        <br/>
        <br/>
        For information on prior updates please us at <strong>info@hostelmatch.com.</strong>
        <br/>
        <br/>
        You can also manage your cookie preferences at any time.
        </div>
      </div>
    </div>
    );
}


export default CookiePolicy;